# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2016 Imagination Technologies
# Copyright (C) 2019 Loongson Technologies

obj-y += checkboard.o
obj-y += ddr.o
obj-y += dt.o
obj-y += lowlevel_init.o
